### ISSUE TITLE
Drag limits

### ISSUE THREAD

**Issue by annanharry** [ndragun92/os-windows11#11]
Hi, I was checking out the project and I am wondering if it is possible to have drag limits, like I accidentally drag the browser too high and could not retrieve it.

**Comment by ndragun92** [comment]
Thanks for raising the first issue :)
Well, yea I have it already in my TODO list to make a smart window offscreen check to bring it back in a visible area automatically. But I will try to implement the w11 usual approach for that which is to right-click on the button in the nav to bring it back.

Will try to work on that today and once I push changes I will let you know

**Comment by annanharry** [comment]
The smart window offscreen check is a great idea to solve this.

**Comment by ndragun92** [comment]
@annanharry Please let me know if the new solution works well for you. I have just deployed a new version :)

**Comment by annanharry** [comment]
Yeah, it works mate. the windows do not get stuck above the screen limits.
